networks:
  testcube:
    name: testcube

services:
  app:
    container_name: testcube-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - postgres
    networks:
      - testcube

  postgres:
    container_name: testcube-db
    image: postgres:15
    restart: always
    volumes:
      - ./docker/postgres/data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - testcube

  web:
    container_name: testcube-web
    image: nginx:stable-alpine
    restart: always
    ports:
      - "85:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - testcube
